
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: omio/gcr.io.kaniko-project.executor:debug
      options: --entrypoint ""
    steps:
      - name: Test cmd
        run: env

