
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      options: --entrypoint ""
    steps:
      - name: Test cmd
        run: /kaniko/executor --context . --dockerfile "Dockerfile" --destination "test/nginx:latest"

